- name: Hadoop Tutorial
  entries:
    - name: Clone Landoop Intro Repo
      command: git clone https://gitlab.com/landoop/landoop-intro.git
      workdir: /home/coyote

    - name: hdfs put
      command: hadoop fs -put ../README.md input.md
      workdir: /home/coyote/landoop-intro/Hadoop-101

    - name: wordcount example
      command: hadoop jar hadoop-examples.jar wordcount input.md results
      workdir: /home/coyote/landoop-intro/Hadoop-101

    - name: build code
      command: hadoop com.sun.tools.javac.Main WordCount.java
      workdir: /home/coyote/landoop-intro/Hadoop-102

    - name: create jar
      command: jar cf wc.jar WordCount.class WordCount$IntSumReducer.class WordCount$TokenizerMapper.class
      workdir: /home/coyote/landoop-intro/Hadoop-102

    - name: run jar
      command: hadoop jar wc.jar WordCount input.md results-2
      workdir: /home/coyote/landoop-intro/Hadoop-102

    - command: hadoop fs -rm -r input.md results results-2
      nolog: true

- name: Sqoop Tutorial
  entries:
    - name: import
      command: |
        sqoop-import --connect jdbc:mysql://mariadb.landoop.com/northwind
                     --username data --password base
                     --table Orders --m 1

    - command: hadoop fs -rm -r Orders
      nolog: true

    - name: hive create db
      command: hive -e "CREATE DATABASE coyote_tutorial"

    - name: import into hive
      command: |
        sqoop import -jt local --connect jdbc:mysql://mariadb.landoop.com/northwind
                     --username data --password base
                     --query 'SELECT * FROM Orders WHERE $CONDITIONS' --m 1
                     --target-dir temp-orders --create-hive-table
                     --hive-table "coyote_tutorial.orders" --hive-import
                     --hive-overwrite --create-hive-table

    - name: drop hive database
      command: hive -e "USE coyote_tutorial; DROP TABLE orders; DROP DATABASE coyote_tutorial"

- name: Kafka Tests
  entries:
    - name: Cloudera Env Vars (no fail)
      command: |
        bash -c '
        echo -e "\
        Zookeeper (ZK) $ZK\n\
        Broker List (BL) $BL\n\
        Bootstrap Server (BS) $BS\n\
        JAAS Login Configuration File (JAAS) $JAAS\n\
        producer.properties path (PROD_PR) $PROD_PR\n\
        consumer.properties path (CONS_PR) $CONS_PR\n\
        KAFKA_OPTS (KAFKA_OPTS) $KAFKA_OPTS"'

    - name: Cloudera Perf Test (Kerberos)
      command: |
        /opt/confluent-2.0.1/bin/kafka-producer-perf-test --topic test-rep-one --throughput 100000 --record-size 1000 --num-records 1000000
        --producer-props bootstrap.servers="cloudera.landoop.com:9092" security.protocol=SASL_PLAINTEXT

    - name: Confluent Perf Test (Non-Kerberos)
      command: |
        /opt/confluent-2.0.1/bin/kafka-producer-perf-test --topic test-rep-one --throughput 100000 --record-size 1000 --num-records 1000000
        --producer-props bootstrap.servers="cloudera.landoop.com:29092"

    - command: rm -rf /home/coyote/landoop-intro
      nolog: true
